### ISSUE TITLE
Consider adding your blog to diff.blog

### ISSUE THREAD

**Issue by diffblog** [ryanbranch/ryanbranch.github.io#3]
Hello :wave: :wave:

Over the past decade, we have seen the rise of centralized publishing platforms like Medium.  A lot of self hosted blogs were migrated to these platforms in hope of a bigger audience. Sadly, most of these blogs lost their unique identity and became just another page on them.

Our mission is to fight back against monopolies like Medium and promote independent self hosted blogs like yours. We think the best way to make this happen is by improving the visibility and reach of self hosted blogs. And that's why we built [diff.blog](https://diff.blog).

diff.blog is an aggregator of developer blogs. It was started in 2019 to improve the visibility of self hosted blogs. Whenever you publish a new blog post on your blog, it would automatically appear in the diff.blog news feed. The title and summary of the post would be visible to the users of diff.blog and they can click on the post to read the full post on your blog.

We also have a weekly email digest, which would email the most popular blog posts in our index to all diff.blog users.

diff.blog index over 637 blogs at the moment. And our network is growing steadily every day. And we would like to invite you to include your blog in diff.blog as well.

Adding your blog to diff.blog is super easy and takes less than a minute.
* Go to https://diff.blog
* Sign up with your GitHub account.
* Go to blog settings https://diff.blog/account/settings/blog/
* Add the URL of your blog

We are looking forward to have your blog in diff.blog. Let us know if you have any questions. Happy to answer.

**Comment by ryanbranch** [comment]
@diffblog Thanks for the information! I checked out your platform and it does look interesting to me.

Currently my website is still under construction, and I'd rather not join the platform until it's fully ready for more public traffic. But I will certainly consider it towards the end of this year when I finish development.

Do you have a means of joining without GitHub Authentication? Or somewhere where I can read more about data privacy and the specific usage of my GitHub account by your service? I prefer not to link individual services whenever possible, and would rather sign up with an email address independent of this account.

**Comment by ryanbranch** [comment]
Closing for now to clear triage; feel free to continue conversation below.

**Comment by diffblog** [comment]
> Currently my website is still under construction, and I'd rather not join the platform until it's fully ready for more public traffic. But I will certainly consider it towards the end of this year when I finish development

Cool. Makes sense :)

>,Do you have a means of joining without GitHub Authentication?

Sorry. diff.blog only support auth using GitHub at the moment. My reasoning was that if I know the GitHub username, I can use the the public info like users you follow, languages you use etc from GitHub to make better recommendations to users.

> Or somewhere where I can read more about data privacy and the specific usage of my GitHub account by your service? I prefer not to link individual services whenever possible, and would rather sign up with an email address independent of this account.

diff.blog don't have any separate page for privacy yet. But diff.blog only fetches email and public info like people you follow, languages you use etc from your profile. The email is used only for sending the weekly digest to users as mentioned above.
https://diff.blog/FAQ/ has more details on diff.blog.

Let me know if you have any more questions :)

**Comment by ryanbranch** [comment]
@diffblog thanks for the explanation. That seems pretty reasonable to me. I'll absolutely keep this in mind for the future.
